package testcases;
import java.io.FileNotFoundException;
import java.io.IOException;

import org.testng.annotations.BeforeClass;

import wrappers.PcorpWrappers;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import pages.LoginPage;

//whether user is able to login successfully and navigate to all pages.

public class TC008_Reporting_ProductionReports extends PcorpWrappers{
	
	@Test(dataProvider="fetchData")
public void login(String emailid,String password,String breadcrumbs1,String breadcrumbs2,String breadcrumbs3,String breadcrumbs4,String threvalue  ) throws InterruptedException, FileNotFoundException, IOException {

		new LoginPage()
		.enterUsername(emailid)
		.enterPassword(password)
		.clickLoginButton()
		.clickHumburger()
		.clickMenu8()
		.clickMenu83()
		.Verifybreadcrumbs("Reports")
		.ClickRoutesaturationReportElectric()
		.clickStartdate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeader("District/Route Saturation Report")
		.ClickInstallerProductivityReportElectric()
		.clickStartingFromDate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeader("100-MTE Installer Performance Report")
		.ClickProductQAReportElectric()
		.clickStartdate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilterBtn()
		.VerifyReportHeader("Quality Assurance Report")
		.ClickProductionReportElectric()
		.clickStartdate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeader("Production Report")
		.ClickProductionDetailReportElectric()
		.clickStartdate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeader("Production Detail Report")
		.ClickInventoryReportElectric()
		.VerifyReportHeaderIR("Inventory Report")
//		.ClickBillingReport()
//		.clickStartdate()
//		.clickPreviousmonth()
//		.pickDate()
//		.clickFilter()
//		.VerifyReportHeaderBR("Billing Report")
//		.ClickTimeTrackingReport()
//		.clickStartdate()
//		.clickPreviousmonth()
//		.pickDate()
//		.clickFilter()
//		.VerifyReportHeaderTTR("")
//		.ClickCallCenterReport()
//		.clickStartdate()
//		.clickPreviousmonth()
//		.pickDate()
//		.clickFilter()
//		.VerifyReportHeaderCCR("Call Center Report")
		.ClickRTUescalationReportElectric()
		.clickEscalateStartdate()
		.clickEscalatePreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeaderRTU("RTU Escalation Report")
		.ClickPERandCommReportElectric()
		.clickFilter()
		.VerifyReportHeaderPER("Customize PER and Communication Report")
		.ClickFieldEscalationReportElectric()
		.VerifyReportHeaderFER("Problem Escalations Report")
		.ClickInstallerTimetrackingReport()
		.clickStartdate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeaderITTR("Installer Time Tracking Report")
		.ClickInstallerTimetrackingdetail()
		.clickStartdate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeaderITTD("Installer Time Tracking Detail Report")
		.ClickMissedApptReport()
		.clickFilter()
		.VerifyReportHeaderMAR("Unassigned and Missed Appointments Report")
		.ClickInventoryReconcileReport()
		.clickSave()
		.ClickExcel()
		.VerifyReportHeaderIIR("")
//		.ClickAdapterInstalledReport()
//		.clickAIRStartdate()
//		.clickAIRPreviousmonth()
//		.pickDate()
//		.clickFilter()
//		.VerifyReportHeaderAIR("Adapter Installed Report")
		.ClickRTUstatusReport()
		.clickFilterBtn()
		.VerifyReportHeaderRTUS("RTU Status Report")
	    .ClickSafetyReport()
	    .clickStartdatePopup()
	    .clickPreviousmonthPopup()
	    .pickDate()
	    .clickFilterBtn()
	    .VerifyReportHeaderSR("")
	    .ClickGPSlocation()
	    .clickGPSStartdatePopup()
	    .clickGPSPreviousmonthPopup()
	    .pickDate()
	    .clickFilter()
	    .VerifyReportHeaderGPS("GPS Location Report")
	    .ClickCallCenterEfficiencyReport()
	    .clickEscalateStartdate()
	    .clickEscalatePreviousmonth()
	    .pickDate()
	    .clickFilter()
	    .VerifyReportHeaderCER("Call Center Efficiency Report")
	    .ClickJawTensionClipReport()
	    .clickAIRStartdate()
	    .clickAIRPreviousmonth()
	    .pickDate()
	    .clickFilter()
	    .VerifyReportHeaderJTC("")
	    .ClickCustomerCommunicationDetail()
	    .SelectComparator(">")
	    .enterVisitcount("2")
	    .clickSearchButton()
	    .ClickTimesheetdata()
	    .clickStartdate()
	    .clickPreviousmonth()
	    .pickDate()
	    .clickFilter()
	    .VerifyReportHeaderTSD("")
	    .ClickInstallationdata()
		.clickStartdate()
		.clickPreviousmonth()
		.pickDate()
		.clickFilter()
		.VerifyReportHeaderID("")
		.ExpandReports()
		.ExpandDatafeedReports()
		.ExpandReports()
		.clickLogoff()
		
		;
	}
	
@BeforeClass
public void beforeClass() {
dataSheetName="AddThresold";
testCaseName="All ProductionReport Verification";
testDescription="Check that user is able to open all the links from Reporting Menu";
}
}
